
dict_expression = {
    'ratio_median': "float(b('nir_median') / b('red_median'))",
    'ratio_median_wet': "float(b('nir_median_wet') / b('red_median_wet'))",
    'ratio_median_dry': "float(b('nir_median_dry') / b('red_median_dry'))",
    'rvi_median': "float(b('red_median') / b('nir_median'))",
    'rvi_median_wet': "float(b('red_median_wet') / b('nir_median_wet'))",
    'rvi_median_dry': "float(b('red_median_dry') / b('nir_median_dry'))",
    'ndvi_median': "float(b('nir_median') - b('red_median')) / (b('nir_median') + b('red_median'))",
    'ndvi_median_wet': "float(b('nir_median_wet') - b('red_median_wet')) / (b('nir_median_wet') + b('red_median_wet'))",
    'ndvi_median_dry': "float(b('nir_median_dry') - b('red_median_dry')) / (b('nir_median_dry') + b('red_median_dry'))",
    'ndbi_median': "float(b('swir1_median') - b('nir_median')) / (b('swir1_median') + b('nir_median'))",
    'ndbi_median_wet': "float(b('swir1_median_wet') - b('nir_median_wet')) / (b('swir1_median_wet') + b('nir_median_wet'))",
    'ndbi_median_dry': "float(b('swir1_median_dry') - b('nir_median_dry')) / (b('swir1_median_dry') + b('nir_median_dry'))",
    'ndmi_median': "float(b('nir_median') - b('swir1_median')) / (b('nir_median') + b('swir1_median'))",
    'ndmi_median_wet': "float(b('nir_median_wet') - b('swir1_median_wet')) / (b('nir_median_wet') + b('swir1_median_wet'))",
    'ndmi_median_dry': "float(b('nir_median_dry') - b('swir1_median_dry')) / (b('nir_median_dry') + b('swir1_median_dry'))",
    'nbr_median': "float(b('nir_median') - b('swir1_median')) / (b('nir_median') + b('swir1_median'))",
    'nbr_median_wet': "float(b('nir_median_wet') - b('swir1_median_wet')) / (b('nir_median_wet') + b('swir1_median_wet'))",
    'nbr_median_dry': "float(b('nir_median_dry') - b('swir1_median_dry')) / (b('nir_median_dry') + b('swir1_median_dry'))",
    'ndti_median': "float(b('swir1_median') - b('swir2_median')) / (b('swir1_median') + b('swir2_median'))",
    'ndti_median_wet': "float(b('swir1_median_wet') - b('swir2_median_wet')) / (b('swir1_median_wet') + b('swir2_median_wet'))",
    'ndti_median_dry': "float(b('swir1_median_dry') - b('swir2_median_dry')) / (b('swir1_median_dry') + b('swir2_median_dry'))",
    'ndwi_median': "float(b('nir_median') - b('swir2_median')) / (b('nir_median') + b('swir2_median'))",
    'ndwi_median_wet': "float(b('nir_median_wet') - b('swir2_median_wet')) / (b('nir_median_wet') + b('swir2_median_wet'))",
    'ndwi_median_dry': "float(b('nir_median_dry') - b('swir2_median_dry')) / (b('nir_median_dry') + b('swir2_median_dry'))",
    "awei_median": "float(4 * (b('green_median') - b('swir2_median')) - (0.25 * b('nir_median') + 2.75 * b('swir1_median')))",
    "awei_median_wet": "float(4 * (b('green_median_wet') - b('swir2_median_wet')) - (0.25 * b('nir_median_wet') + 2.75 * b('swir1_median_wet')))",
    "awei_median_dry": "float(4 * (b('green_median_dry') - b('swir2_median_dry')) - (0.25 * b('nir_median_dry') + 2.75 * b('swir1_median_dry')))",
    "iia_median": "float((b('green_median') - 4 *  b('nir_median')) / (b('green_median') + 4 *  b('nir_median')))",
    "iia_median_wet": "float((b('green_median_wet') - 4 *  b('nir_median_wet')) / (b('green_median_wet') + 4 *  b('nir_median_wet')))",
    "iia_median_dry": "float((b('green_median_dry') - 4 *  b('nir_median_dry')) / (b('green_median_dry') + 4 *  b('nir_median_dry')))",
    'evi_median': "float(2.4 * (b('nir_median') - b('red_median')) / (1 + b('nir_median') + b('red_median')))",
    'evi_median_wet': "float(2.4 * (b('nir_median_wet') - b('red_median_wet')) / (1 + b('nir_median_wet') + b('red_median_wet')))",
    'evi_median_dry': "float(2.4 * (b('nir_median_dry') - b('red_median_dry')) / (1 + b('nir_median_dry') + b('red_median_dry')))",
    'gvmi_median': "float ((b('nir_median')  + 0.1) - (b('swir1_median') + 0.02)) / ((b('nir_median') + 0.1) + (b('swir1_median') + 0.02))",
    'gvmi_median_wet': "float ((b('nir_median_wet')  + 0.1) - (b('swir1_median_wet') + 0.02)) / ((b('nir_median_wet') + 0.1) + (b('swir1_median_wet') + 0.02))",
    'gvmi_median_dry': "float ((b('nir_median_dry')  + 0.1) - (b('swir1_median_dry') + 0.02)) / ((b('nir_median_dry') + 0.1) + (b('swir1_median_dry') + 0.02))",
    'gcvi_median': "float(b('nir_median')) / (b('green_median')) - 1",
    'gcvi_median_wet': "float(b('nir_median_wet')) / (b('green_median_wet')) - 1",
    'gcvi_median_dry': "float(b('nir_median_dry')) / (b('green_median_dry')) - 1",
    'gemi_median': "float((2 * (b('nir_median') * b('nir_median') - b('red_median') * b('red_median')) + 1.5 * b('nir_median') + 0.5 * b('red_median')) / (b('nir_median') + b('green_median') + 0.5) )",
    'gemi_median_wet': "float((2 * (b('nir_median_wet') * b('nir_median_wet') - b('red_median_wet') * b('red_median_wet')) + 1.5 * b('nir_median_wet') + 0.5 * b('red_median_wet')) / (b('nir_median_wet') + b('green_median_wet') + 0.5) )",
    'gemi_median_dry':  "float((2 * (b('nir_median_dry') * b('nir_median_dry') - b('red_median_dry') * b('red_median_dry')) + 1.5 * b('nir_median_dry') + 0.5 * b('red_median_dry')) / (b('nir_median_dry') + b('green_median_dry') + 0.5) )",
    'cvi_median': "float(b('nir_median') * (b('green_median') / (b('blue_median') * b('blue_median'))))",
    'cvi_median_wet': "float(b('nir_median_wet') * (b('green_median_wet') / (b('blue_median_wet') * b('blue_median_wet'))))",
    'cvi_median_dry': "float(b('nir_median_dry') * (b('green_median_dry') / (b('blue_median_dry') * b('blue_median_dry'))))",
    'gli_median': "float((2 * b('green_median') - b('red_median') - b('blue_median')) / (2 * b('green_median') + b('red_median') + b('blue_median')))",
    'gli_median_wet': "float((2 * b('green_median_wet') - b('red_median_wet') - b('blue_median_wet')) / (2 * b('green_median_wet') + b('red_median_wet') + b('blue_median_wet')))",
    'gli_median_dry': "float((2 * b('green_median_dry') - b('red_median_dry') - b('blue_median_dry')) / (2 * b('green_median_dry') + b('red_median_dry') + b('blue_median_dry')))",
    'shape_median': "float((2 * b('red_median') - b('green_median') - b('blue_median')) / (b('green_median') - b('blue_median')))",
    'shape_median_wet': "float((2 * b('red_median_wet') - b('green_median_wet') - b('blue_median_wet')) / (b('green_median_wet') - b('blue_median_wet')))",
    'shape_median_dry': "float((2 * b('red_median_dry') - b('green_median_dry') - b('blue_median_dry')) / (b('green_median_dry') - b('blue_median_dry')))",
    'afvi_median': "float((b('nir_median') - 0.5 * b('swir2_median')) / (b('nir_median') + 0.5 * b('swir2_median')))",
    'afvi_median_wet': "float((b('nir_median_wet') - 0.5 * b('swir2_median_wet')) / (b('nir_median_wet') + 0.5 * b('swir2_median_wet')))",
    'afvi_median_dry': "float((b('nir_median_dry') - 0.5 * b('swir2_median_dry')) / (b('nir_median_dry') + 0.5 * b('swir2_median_dry')))",
    'avi_median': "float((b('nir_median')* (1.0 - b('red_median')) * (b('nir_median') - b('red_median'))) ** 1/3)",
    'avi_median_wet': "float((b('nir_median_wet')* (1.0 - b('red_median_wet')) * (b('nir_median_wet') - b('red_median_wet'))) ** 1/3)",
    'avi_median_dry': "float((b('nir_median_dry')* (1.0 - b('red_median_dry')) * (b('nir_median_dry') - b('red_median_dry'))) ** 1/3)",
    'nddi_median': "float((b('ndvi_median') - b('ndwi_median')) / (b('ndvi_median') + b('ndwi_median')))",
    'nddi_median_wet': "float((b('ndvi_median_wet') - b('ndwi_median_wet')) / (b('ndvi_median_wet') + b('ndwi_median_wet')))",
    'nddi_median_dry': "float((b('ndvi_median_dry') - b('ndwi_median_dry')) / (b('ndvi_median_dry') + b('ndwi_median_dry')))",
    'bsi_median': "float(((b('swir1_median') - b('red_median')) - (b('nir_median') + b('blue_median'))) / ((b('swir1_median') + b('red_median')) + (b('nir_median') + b('blue_median'))))",
    'bsi_median_wet': "float(((b('swir1_median') - b('red_median')) - (b('nir_median') + b('blue_median'))) / ((b('swir1_median') + b('red_median')) + (b('nir_median') + b('blue_median'))))",
    'bsi_median_dry': "float(((b('swir1_median') - b('red_median')) - (b('nir_median') + b('blue_median'))) / ((b('swir1_median') + b('red_median')) + (b('nir_median') + b('blue_median'))))",
    'brba_median': "float(b('red_median') / b('swir1_median'))",
    'brba_median_wet': "float(b('red_median_wet') / b('swir1_median_wet'))",
    'brba_median_dry': "float(b('red_median_dry') / b('swir1_median_dry'))",
    'dswi5_median': "float((b('nir_median') + b('green_median')) / (b('swir1_median') + b('red_median')))",
    'dswi5_median_wet': "float((b('nir_median_wet') + b('green_median_wet')) / (b('swir1_median_wet') + b('red_median_wet')))",
    'dswi5_median_dry': "float((b('nir_median_dry') + b('green_median_dry')) / (b('swir1_median_dry') + b('red_median_dry')))",
    'lswi_median': "float((b('nir_median') - b('swir1_median')) / (b('nir_median') + b('swir1_median')))",
    'lswi_median_wet': "float((b('nir_median_wet') - b('swir1_median_wet')) / (b('nir_median_wet') + b('swir1_median_wet')))",
    'lswi_median_dry': "float((b('nir_median_dry') - b('swir1_median_dry')) / (b('nir_median_dry') + b('swir1_median_dry')))",
    'mbi_median': "float(((b('swir1_median') - b('swir2_median') - b('nir_median')) / (b('swir1_median') + b('swir2_median') + b('nir_median'))) + 0.5)",
    'mbi_median_wet': "float(((b('swir1_median_wet') - b('swir2_median_wet') - b('nir_median_wet')) / (b('swir1_median_wet') + b('swir2_median_wet') + b('nir_median_wet'))) + 0.5)",
    'mbi_median_dry': "float(((b('swir1_median_dry') - b('swir2_median_dry') - b('nir_median_dry')) / (b('swir1_median_dry') + b('swir2_median_dry') + b('nir_median_dry'))) + 0.5)",
    'ui_median': "float((b('swir2_median') - b('nir_median')) / (b('swir2_median') + b('nir_median')))",
    'ui_median_wet': "float((b('swir2_median_wet') - b('nir_median_wet')) / (b('swir2_median_wet') + b('nir_median_wet')))",
    'ui_median_dry': "float((b('swir2_median_dry') - b('nir_median_dry')) / (b('swir2_median_dry') + b('nir_median_dry')))",
    'osavi_median': "float(b('nir_median') - b('red_median')) / (0.16 + b('nir_median') + b('red_median'))",
    'osavi_median_wet': "float(b('nir_median_wet') - b('red_median_wet')) / (0.16 + b('nir_median_wet') + b('red_median_wet'))",
    'osavi_median_dry': "float(b('nir_median_dry') - b('red_median_dry')) / (0.16 + b('nir_median_dry') + b('red_median_dry'))",
    'msavi_median': "float((2 * b('nir_median') + 1 - sqrt((2 * b('nir_median') + 1) * (2 * b('nir_median') + 1) - 8 * (b('nir_median') - b('red_median'))))/2)",
    'msavi_median_wet': "float((2 * b('nir_median_wet') + 1 - sqrt((2 * b('nir_median_wet') + 1) * (2 * b('nir_median_wet') + 1) - 8 * (b('nir_median_wet') - b('red_median_wet'))))/2)",
    'msavi_median_dry': "float((2 * b('nir_median_dry') + 1 - sqrt((2 * b('nir_median_dry') + 1) * (2 * b('nir_median_dry') + 1) - 8 * (b('nir_median_dry') - b('red_median_dry'))))/2)",
    'gsavi_median': "float(b('nir_median') - b('green_median')) / ((0.5 + b('nir_median') + b('green_median')) * 1.5)",
    'gsavi_median_wet': "float(b('nir_median_wet') - b('green_median_wet')) / ((0.5 + b('nir_median_wet') + b('green_median_wet')) * 1.5)",
    'gsavi_median_dry': "float(b('nir_median_dry') - b('green_median_dry')) / ((0.5 + b('nir_median_dry') + b('green_median_dry')) * 1.5)",
    'ri_median': "float(b('nir_median') - b('green_median')) / (b('nir_median') + b('green_median'))",
    'ri_median_wet': "float(b('nir_median_wet') - b('green_median_wet')) / (b('nir_median_wet') + b('green_median_wet'))",
    'ri_median_dry': "float(b('nir_median_dry') - b('green_median_dry')) / (b('nir_median_dry') + b('green_median_dry'))",
    'brightness_median': "float(0.3037 * b('blue_median') + 0.2793 * b('green_median') + 0.4743 * b('red_median')  + 0.5585 * b('nir_median') + 0.5082 * b('swir1_median') +  0.1863 * b('swir2_median'))",
    'brightness_median_wet': "float(0.3037 * b('blue_median_wet') + 0.2793 * b('green_median_wet') + 0.4743 * b('red_median_wet') + 0.5585 * b('nir_median_wet') + 0.5082 * b('swir1_median_wet') +  0.1863 * b('swir2_median_wet'))",
    'brightness_median_dry': "float(0.3037 * b('blue_median_dry') + 0.2793 * b('green_median_dry') + 0.4743 * b('red_median_dry') + 0.5585 * b('nir_median_dry') + 0.5082 * b('swir1_median_dry') +  0.1863 * b('swir2_median_dry'))",
    'wetness_median': "float(0.1509 * b('blue_median') + 0.1973 * b('green_median') + 0.3279 * b('red_median')  + 0.3406 * b('nir_median') + 0.7112 * b('swir1_median') +  0.4572 * b('swir2_median'))",
    'wetness_median_wet': "float(0.1509 * b('blue_median_wet') + 0.1973 * b('green_median_wet') + 0.3279 * b('red_median_wet') + 0.3406 * b('nir_median_wet') + 0.7112 * b('swir1_median_wet') +  0.4572 * b('swir2_median_wet'))",
    'wetness_median_dry': "float(0.1509 * b('blue_median_dry') + 0.1973 * b('green_median_dry') + 0.3279 * b('red_median_dry') + 0.3406 * b('nir_median_dry') + 0.7112 * b('swir1_median_dry') +  0.4572 * b('swir2_median_dry'))",
    'msi_median': "float( b('nir_median') / b('swir1_median'))",
    'msi_median_wet': "float( b('nir_median_wet') / b('swir1_median_wet'))",
    'msi_median_dry': "float( b('nir_median_dry') / b('swir1_median_dry'))",
    'spri_median': "float(((b('green_median') - b('blue_median')) / (b('green_median') + b('blue_median'))) + 1) / 2",
    'spri_median_wet': "float(((b('green_median_wet') - b('blue_median_wet')) / (b('green_median_wet') + b('blue_median_wet'))) + 1) / 2",
    'spri_median_dry': "float(((b('green_median') - b('blue_median')) / (b('green_median') + b('blue_median'))) + 1) / 2",
    'co2flux_median': "float(b('ndvi_median') * b('spri_median'))",
    'co2flux_median_wet': "float(b('ndvi_median_wet') * b('spri_median_wet'))",
    'co2flux_median_dry': "float(b('ndvi_median_dry') * b('spri_median_dry'))",
}